/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SaccosRouteImport } from './routes/saccos'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransparencyIndexRouteImport } from './routes/transparency.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as SaccosIndexRouteImport } from './routes/saccos.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as ImpactIndexRouteImport } from './routes/impact.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as TransparencyReportsRouteImport } from './routes/transparency.reports'
import { Route as ServicesTrainingRouteImport } from './routes/services.training'
import { Route as ServicesSavingsRouteImport } from './routes/services.savings'
import { Route as ServicesLoansRouteImport } from './routes/services.loans'
import { Route as ServicesInvestmentsRouteImport } from './routes/services.investments'
import { Route as ServicesInsuranceRouteImport } from './routes/services.insurance'
import { Route as SaccosJoinRouteImport } from './routes/saccos.join'
import { Route as SaccosBenefitsRouteImport } from './routes/saccos.benefits'
import { Route as ResourcesPublicationsRouteImport } from './routes/resources.publications'
import { Route as ResourcesPoliciesRouteImport } from './routes/resources.policies'
import { Route as ResourcesFormsRouteImport } from './routes/resources.forms'
import { Route as ResourcesFaqRouteImport } from './routes/resources.faq'
import { Route as ResourcesAuditsRouteImport } from './routes/resources.audits'
import { Route as NewsGalleryRouteImport } from './routes/news.gallery'
import { Route as NewsEventsRouteImport } from './routes/news.events'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ImpactStatsRouteImport } from './routes/impact.stats'
import { Route as AboutHistoryRouteImport } from './routes/about.history'
import { Route as AboutGovernanceRouteImport } from './routes/about.governance'
import { Route as ResourcesKindSlugRouteImport } from './routes/resources.$kind.$slug'
import { Route as NewsEventsSlugRouteImport } from './routes/news.events.$slug'
import { Route as ImpactStoriesSlugRouteImport } from './routes/impact.stories.$slug'
import { Route as AboutPeopleSlugRouteImport } from './routes/about.people.$slug'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SaccosRoute = SaccosRouteImport.update({
  id: '/saccos',
  path: '/saccos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyIndexRoute = TransparencyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransparencyRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const SaccosIndexRoute = SaccosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SaccosRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const ImpactIndexRoute = ImpactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImpactRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const TransparencyReportsRoute = TransparencyReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TransparencyRoute,
} as any)
const ServicesTrainingRoute = ServicesTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSavingsRoute = ServicesSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLoansRoute = ServicesLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInvestmentsRoute = ServicesInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInsuranceRoute = ServicesInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => ServicesRoute,
} as any)
const SaccosJoinRoute = SaccosJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => SaccosRoute,
} as any)
const SaccosBenefitsRoute = SaccosBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => SaccosRoute,
} as any)
const ResourcesPublicationsRoute = ResourcesPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesPoliciesRoute = ResourcesPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesFormsRoute = ResourcesFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesFaqRoute = ResourcesFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesAuditsRoute = ResourcesAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => ResourcesRoute,
} as any)
const NewsGalleryRoute = NewsGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => NewsRoute,
} as any)
const NewsEventsRoute = NewsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ImpactStatsRoute = ImpactStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ImpactRoute,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AboutRoute,
} as any)
const AboutGovernanceRoute = AboutGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AboutRoute,
} as any)
const ResourcesKindSlugRoute = ResourcesKindSlugRouteImport.update({
  id: '/$kind/$slug',
  path: '/$kind/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const NewsEventsSlugRoute = NewsEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsEventsRoute,
} as any)
const ImpactStoriesSlugRoute = ImpactStoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => ImpactRoute,
} as any)
const AboutPeopleSlugRoute = AboutPeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/saccos': typeof SaccosRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/transparency': typeof TransparencyRouteWithChildren
  '/about/governance': typeof AboutGovernanceRoute
  '/about/history': typeof AboutHistoryRoute
  '/impact/stats': typeof ImpactStatsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/events': typeof NewsEventsRouteWithChildren
  '/news/gallery': typeof NewsGalleryRoute
  '/resources/audits': typeof ResourcesAuditsRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/forms': typeof ResourcesFormsRoute
  '/resources/policies': typeof ResourcesPoliciesRoute
  '/resources/publications': typeof ResourcesPublicationsRoute
  '/saccos/benefits': typeof SaccosBenefitsRoute
  '/saccos/join': typeof SaccosJoinRoute
  '/services/insurance': typeof ServicesInsuranceRoute
  '/services/investments': typeof ServicesInvestmentsRoute
  '/services/loans': typeof ServicesLoansRoute
  '/services/savings': typeof ServicesSavingsRoute
  '/services/training': typeof ServicesTrainingRoute
  '/transparency/reports': typeof TransparencyReportsRoute
  '/about/': typeof AboutIndexRoute
  '/impact/': typeof ImpactIndexRoute
  '/news/': typeof NewsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/saccos/': typeof SaccosIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/transparency/': typeof TransparencyIndexRoute
  '/about/people/$slug': typeof AboutPeopleSlugRoute
  '/impact/stories/$slug': typeof ImpactStoriesSlugRoute
  '/news/events/$slug': typeof NewsEventsSlugRoute
  '/resources/$kind/$slug': typeof ResourcesKindSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/history': typeof AboutHistoryRoute
  '/impact/stats': typeof ImpactStatsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/events': typeof NewsEventsRouteWithChildren
  '/news/gallery': typeof NewsGalleryRoute
  '/resources/audits': typeof ResourcesAuditsRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/forms': typeof ResourcesFormsRoute
  '/resources/policies': typeof ResourcesPoliciesRoute
  '/resources/publications': typeof ResourcesPublicationsRoute
  '/saccos/benefits': typeof SaccosBenefitsRoute
  '/saccos/join': typeof SaccosJoinRoute
  '/services/insurance': typeof ServicesInsuranceRoute
  '/services/investments': typeof ServicesInvestmentsRoute
  '/services/loans': typeof ServicesLoansRoute
  '/services/savings': typeof ServicesSavingsRoute
  '/services/training': typeof ServicesTrainingRoute
  '/transparency/reports': typeof TransparencyReportsRoute
  '/about': typeof AboutIndexRoute
  '/impact': typeof ImpactIndexRoute
  '/news': typeof NewsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/saccos': typeof SaccosIndexRoute
  '/services': typeof ServicesIndexRoute
  '/transparency': typeof TransparencyIndexRoute
  '/about/people/$slug': typeof AboutPeopleSlugRoute
  '/impact/stories/$slug': typeof ImpactStoriesSlugRoute
  '/news/events/$slug': typeof NewsEventsSlugRoute
  '/resources/$kind/$slug': typeof ResourcesKindSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/saccos': typeof SaccosRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/transparency': typeof TransparencyRouteWithChildren
  '/about/governance': typeof AboutGovernanceRoute
  '/about/history': typeof AboutHistoryRoute
  '/impact/stats': typeof ImpactStatsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/events': typeof NewsEventsRouteWithChildren
  '/news/gallery': typeof NewsGalleryRoute
  '/resources/audits': typeof ResourcesAuditsRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/forms': typeof ResourcesFormsRoute
  '/resources/policies': typeof ResourcesPoliciesRoute
  '/resources/publications': typeof ResourcesPublicationsRoute
  '/saccos/benefits': typeof SaccosBenefitsRoute
  '/saccos/join': typeof SaccosJoinRoute
  '/services/insurance': typeof ServicesInsuranceRoute
  '/services/investments': typeof ServicesInvestmentsRoute
  '/services/loans': typeof ServicesLoansRoute
  '/services/savings': typeof ServicesSavingsRoute
  '/services/training': typeof ServicesTrainingRoute
  '/transparency/reports': typeof TransparencyReportsRoute
  '/about/': typeof AboutIndexRoute
  '/impact/': typeof ImpactIndexRoute
  '/news/': typeof NewsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/saccos/': typeof SaccosIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/transparency/': typeof TransparencyIndexRoute
  '/about/people/$slug': typeof AboutPeopleSlugRoute
  '/impact/stories/$slug': typeof ImpactStoriesSlugRoute
  '/news/events/$slug': typeof NewsEventsSlugRoute
  '/resources/$kind/$slug': typeof ResourcesKindSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/news'
    | '/resources'
    | '/saccos'
    | '/services'
    | '/transparency'
    | '/about/governance'
    | '/about/history'
    | '/impact/stats'
    | '/news/$slug'
    | '/news/events'
    | '/news/gallery'
    | '/resources/audits'
    | '/resources/faq'
    | '/resources/forms'
    | '/resources/policies'
    | '/resources/publications'
    | '/saccos/benefits'
    | '/saccos/join'
    | '/services/insurance'
    | '/services/investments'
    | '/services/loans'
    | '/services/savings'
    | '/services/training'
    | '/transparency/reports'
    | '/about/'
    | '/impact/'
    | '/news/'
    | '/resources/'
    | '/saccos/'
    | '/services/'
    | '/transparency/'
    | '/about/people/$slug'
    | '/impact/stories/$slug'
    | '/news/events/$slug'
    | '/resources/$kind/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/about/governance'
    | '/about/history'
    | '/impact/stats'
    | '/news/$slug'
    | '/news/events'
    | '/news/gallery'
    | '/resources/audits'
    | '/resources/faq'
    | '/resources/forms'
    | '/resources/policies'
    | '/resources/publications'
    | '/saccos/benefits'
    | '/saccos/join'
    | '/services/insurance'
    | '/services/investments'
    | '/services/loans'
    | '/services/savings'
    | '/services/training'
    | '/transparency/reports'
    | '/about'
    | '/impact'
    | '/news'
    | '/resources'
    | '/saccos'
    | '/services'
    | '/transparency'
    | '/about/people/$slug'
    | '/impact/stories/$slug'
    | '/news/events/$slug'
    | '/resources/$kind/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/news'
    | '/resources'
    | '/saccos'
    | '/services'
    | '/transparency'
    | '/about/governance'
    | '/about/history'
    | '/impact/stats'
    | '/news/$slug'
    | '/news/events'
    | '/news/gallery'
    | '/resources/audits'
    | '/resources/faq'
    | '/resources/forms'
    | '/resources/policies'
    | '/resources/publications'
    | '/saccos/benefits'
    | '/saccos/join'
    | '/services/insurance'
    | '/services/investments'
    | '/services/loans'
    | '/services/savings'
    | '/services/training'
    | '/transparency/reports'
    | '/about/'
    | '/impact/'
    | '/news/'
    | '/resources/'
    | '/saccos/'
    | '/services/'
    | '/transparency/'
    | '/about/people/$slug'
    | '/impact/stories/$slug'
    | '/news/events/$slug'
    | '/resources/$kind/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SaccosRoute: typeof SaccosRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  TransparencyRoute: typeof TransparencyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saccos': {
      id: '/saccos'
      path: '/saccos'
      fullPath: '/saccos'
      preLoaderRoute: typeof SaccosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency/': {
      id: '/transparency/'
      path: '/'
      fullPath: '/transparency/'
      preLoaderRoute: typeof TransparencyIndexRouteImport
      parentRoute: typeof TransparencyRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/saccos/': {
      id: '/saccos/'
      path: '/'
      fullPath: '/saccos/'
      preLoaderRoute: typeof SaccosIndexRouteImport
      parentRoute: typeof SaccosRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/impact/': {
      id: '/impact/'
      path: '/'
      fullPath: '/impact/'
      preLoaderRoute: typeof ImpactIndexRouteImport
      parentRoute: typeof ImpactRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/transparency/reports': {
      id: '/transparency/reports'
      path: '/reports'
      fullPath: '/transparency/reports'
      preLoaderRoute: typeof TransparencyReportsRouteImport
      parentRoute: typeof TransparencyRoute
    }
    '/services/training': {
      id: '/services/training'
      path: '/training'
      fullPath: '/services/training'
      preLoaderRoute: typeof ServicesTrainingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/savings': {
      id: '/services/savings'
      path: '/savings'
      fullPath: '/services/savings'
      preLoaderRoute: typeof ServicesSavingsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/loans': {
      id: '/services/loans'
      path: '/loans'
      fullPath: '/services/loans'
      preLoaderRoute: typeof ServicesLoansRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/investments': {
      id: '/services/investments'
      path: '/investments'
      fullPath: '/services/investments'
      preLoaderRoute: typeof ServicesInvestmentsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/insurance': {
      id: '/services/insurance'
      path: '/insurance'
      fullPath: '/services/insurance'
      preLoaderRoute: typeof ServicesInsuranceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/saccos/join': {
      id: '/saccos/join'
      path: '/join'
      fullPath: '/saccos/join'
      preLoaderRoute: typeof SaccosJoinRouteImport
      parentRoute: typeof SaccosRoute
    }
    '/saccos/benefits': {
      id: '/saccos/benefits'
      path: '/benefits'
      fullPath: '/saccos/benefits'
      preLoaderRoute: typeof SaccosBenefitsRouteImport
      parentRoute: typeof SaccosRoute
    }
    '/resources/publications': {
      id: '/resources/publications'
      path: '/publications'
      fullPath: '/resources/publications'
      preLoaderRoute: typeof ResourcesPublicationsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/policies': {
      id: '/resources/policies'
      path: '/policies'
      fullPath: '/resources/policies'
      preLoaderRoute: typeof ResourcesPoliciesRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/forms': {
      id: '/resources/forms'
      path: '/forms'
      fullPath: '/resources/forms'
      preLoaderRoute: typeof ResourcesFormsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/faq': {
      id: '/resources/faq'
      path: '/faq'
      fullPath: '/resources/faq'
      preLoaderRoute: typeof ResourcesFaqRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/audits': {
      id: '/resources/audits'
      path: '/audits'
      fullPath: '/resources/audits'
      preLoaderRoute: typeof ResourcesAuditsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/news/gallery': {
      id: '/news/gallery'
      path: '/gallery'
      fullPath: '/news/gallery'
      preLoaderRoute: typeof NewsGalleryRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/events': {
      id: '/news/events'
      path: '/events'
      fullPath: '/news/events'
      preLoaderRoute: typeof NewsEventsRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/impact/stats': {
      id: '/impact/stats'
      path: '/stats'
      fullPath: '/impact/stats'
      preLoaderRoute: typeof ImpactStatsRouteImport
      parentRoute: typeof ImpactRoute
    }
    '/about/history': {
      id: '/about/history'
      path: '/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/governance': {
      id: '/about/governance'
      path: '/governance'
      fullPath: '/about/governance'
      preLoaderRoute: typeof AboutGovernanceRouteImport
      parentRoute: typeof AboutRoute
    }
    '/resources/$kind/$slug': {
      id: '/resources/$kind/$slug'
      path: '/$kind/$slug'
      fullPath: '/resources/$kind/$slug'
      preLoaderRoute: typeof ResourcesKindSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/news/events/$slug': {
      id: '/news/events/$slug'
      path: '/$slug'
      fullPath: '/news/events/$slug'
      preLoaderRoute: typeof NewsEventsSlugRouteImport
      parentRoute: typeof NewsEventsRoute
    }
    '/impact/stories/$slug': {
      id: '/impact/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/impact/stories/$slug'
      preLoaderRoute: typeof ImpactStoriesSlugRouteImport
      parentRoute: typeof ImpactRoute
    }
    '/about/people/$slug': {
      id: '/about/people/$slug'
      path: '/people/$slug'
      fullPath: '/about/people/$slug'
      preLoaderRoute: typeof AboutPeopleSlugRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutGovernanceRoute: typeof AboutGovernanceRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AboutPeopleSlugRoute: typeof AboutPeopleSlugRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutGovernanceRoute: AboutGovernanceRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  AboutIndexRoute: AboutIndexRoute,
  AboutPeopleSlugRoute: AboutPeopleSlugRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ImpactRouteChildren {
  ImpactStatsRoute: typeof ImpactStatsRoute
  ImpactIndexRoute: typeof ImpactIndexRoute
  ImpactStoriesSlugRoute: typeof ImpactStoriesSlugRoute
}

const ImpactRouteChildren: ImpactRouteChildren = {
  ImpactStatsRoute: ImpactStatsRoute,
  ImpactIndexRoute: ImpactIndexRoute,
  ImpactStoriesSlugRoute: ImpactStoriesSlugRoute,
}

const ImpactRouteWithChildren =
  ImpactRoute._addFileChildren(ImpactRouteChildren)

interface NewsEventsRouteChildren {
  NewsEventsSlugRoute: typeof NewsEventsSlugRoute
}

const NewsEventsRouteChildren: NewsEventsRouteChildren = {
  NewsEventsSlugRoute: NewsEventsSlugRoute,
}

const NewsEventsRouteWithChildren = NewsEventsRoute._addFileChildren(
  NewsEventsRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsEventsRoute: typeof NewsEventsRouteWithChildren
  NewsGalleryRoute: typeof NewsGalleryRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsEventsRoute: NewsEventsRouteWithChildren,
  NewsGalleryRoute: NewsGalleryRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ResourcesRouteChildren {
  ResourcesAuditsRoute: typeof ResourcesAuditsRoute
  ResourcesFaqRoute: typeof ResourcesFaqRoute
  ResourcesFormsRoute: typeof ResourcesFormsRoute
  ResourcesPoliciesRoute: typeof ResourcesPoliciesRoute
  ResourcesPublicationsRoute: typeof ResourcesPublicationsRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ResourcesKindSlugRoute: typeof ResourcesKindSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesAuditsRoute: ResourcesAuditsRoute,
  ResourcesFaqRoute: ResourcesFaqRoute,
  ResourcesFormsRoute: ResourcesFormsRoute,
  ResourcesPoliciesRoute: ResourcesPoliciesRoute,
  ResourcesPublicationsRoute: ResourcesPublicationsRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ResourcesKindSlugRoute: ResourcesKindSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface SaccosRouteChildren {
  SaccosBenefitsRoute: typeof SaccosBenefitsRoute
  SaccosJoinRoute: typeof SaccosJoinRoute
  SaccosIndexRoute: typeof SaccosIndexRoute
}

const SaccosRouteChildren: SaccosRouteChildren = {
  SaccosBenefitsRoute: SaccosBenefitsRoute,
  SaccosJoinRoute: SaccosJoinRoute,
  SaccosIndexRoute: SaccosIndexRoute,
}

const SaccosRouteWithChildren =
  SaccosRoute._addFileChildren(SaccosRouteChildren)

interface ServicesRouteChildren {
  ServicesInsuranceRoute: typeof ServicesInsuranceRoute
  ServicesInvestmentsRoute: typeof ServicesInvestmentsRoute
  ServicesLoansRoute: typeof ServicesLoansRoute
  ServicesSavingsRoute: typeof ServicesSavingsRoute
  ServicesTrainingRoute: typeof ServicesTrainingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesInsuranceRoute: ServicesInsuranceRoute,
  ServicesInvestmentsRoute: ServicesInvestmentsRoute,
  ServicesLoansRoute: ServicesLoansRoute,
  ServicesSavingsRoute: ServicesSavingsRoute,
  ServicesTrainingRoute: ServicesTrainingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface TransparencyRouteChildren {
  TransparencyReportsRoute: typeof TransparencyReportsRoute
  TransparencyIndexRoute: typeof TransparencyIndexRoute
}

const TransparencyRouteChildren: TransparencyRouteChildren = {
  TransparencyReportsRoute: TransparencyReportsRoute,
  TransparencyIndexRoute: TransparencyIndexRoute,
}

const TransparencyRouteWithChildren = TransparencyRoute._addFileChildren(
  TransparencyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  SaccosRoute: SaccosRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  TransparencyRoute: TransparencyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
